#!/usr/bin/env python

"""

Usage:
     ./riak_util -r <ring_size> -t "<bucket_type>" -b "<bucket>" -k "<key>"

"""

import pkgutil
import importlib
from py_interface import erl_term
from sha import sha

# packages = pkgutil.walk_packages(path='.')
# for importer, name, is_package in packages:
#         mod = importlib.import_module(name)

import sys
import getopt
import riak_utils

def main():
  # parse command line options
  ring_size=None
  bucket_type=None
  bucket=None
  key=None
  try:
      opts, args = getopt.getopt(sys.argv[1:], "hr:t:b:k:", ["help","ring-size","bucket-type","bucket","key"])
  except getopt.error, msg:
    print msg
    helpmsg()
    sys.exit(2)

  if len(opts) < 1:
    helpmsg()
    sys.exit(2)

  #print opts

  # process options
  for o, a in opts:
    if o in ("-h", "--help"):
      print __doc__
      sys.exit(0)
    if o in "-r":
      ring_size = a
    if o in "-b":
      bucket = a
    if o in "-t":
      bucket_type = a
    if o in "-k":
      key = a

  #print "%s - %s" % (oid,ring_size)
  res = riak_utils.whatp(bucket_type,bucket,key,int(ring_size))
  print "Partition placement:" 
  for i,p in res:
      print "%s:%s" % (p,i)

def helpmsg():
    print "for help use --help"
    print "for options use --options"
    print __doc__

if __name__ == "__main__":
  main()
