#!/usr/bin/env python

"""

Usage:
     ./riak_util -r <ring_size> -t "<bucket_type>" -b "<bucket>" -k "<key>"

"""

import pkgutil
import importlib
from py_interface import erl_term
from sha import sha

# packages = pkgutil.walk_packages(path='.')
# for importer, name, is_package in packages:
#         mod = importlib.import_module(name)

import sys
import getopt
import riak_utils

def main():
  # parse command line options
  _ring_size=64
  _bucket_type=None
  _bucket=None
  _key=None
  _n_val=3
  try:
      opts, args = getopt.getopt(sys.argv[1:], "h:n:r:t:b:k:", ["help","nval","ring-size","bucket-type","bucket","key"])
  except getopt.error, msg:
    print msg
    helpmsg()
    sys.exit(2)

  if len(opts) < 1:
    helpmsg()
    sys.exit(2)

  #print opts

  # process options
  for o, a in opts:
    if o in ("-h", "--help"):
      print __doc__
      sys.exit(0)
    if o in "-n":
      _n_val = a
    if o in "-r":
      _ring_size = a
    if o in "-b":
      _bucket = a
    if o in "-t":
      _bucket_type = a
    if o in "-k":
      _key = a

  print "type,bucket,key,ring_size,n_val"
  print _bucket_type,_bucket,_key,_ring_size,_n_val

  if(_bucket_type != None):
    id_hash,partitions = riak_utils.whatp(bucket_type=_bucket_type,bucket=_bucket,key=_key,ring_size=_ring_size,n_val=_n_val) 
  else:
    id_hash,partitions = riak_utils.whatp(bucket=_bucket,key=_key,ring_size=_ring_size,n_val=_n_val) 


  print "id hash:"
  print id_hash
  print "Partition placement:" 

  for i,p in partitions:
      print "%s:%s" % (p,i)

def helpmsg():
    print "for help use --help"
    print "for options use --options"
    print __doc__

if __name__ == "__main__":
  main()
